---
# tasks file for setupvm
# - name: Install Docker from script

- name: Install Docker from script
  ansible.builtin.raw: "curl https://get.docker.com | bash"

- name: Install Packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - jq
    - vim
    - tmux
    - radare2
    - python3
    - python3-pip
    - yara
    - unzip
    - docker-compose
    - p7zip-full
    - libfuzzy-dev
    - libyara-dev

- name: Add vagrant user to group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: true

- name: Install r2pipe via pip
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - r2pipe
    - lief

- name: Set Sysctl VM_MAX_MAP Count
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_set: true
    reload: true

- name: Copy Docker-Compose
  ansible.builtin.copy:
    src: ./files/docker-compose.yml
    dest: /home/vagrant/

- name: Copy Docker-Compose ENV
  ansible.builtin.copy:
    src: ./files/env
    dest: /home/vagrant/.env

# this can cause a hang, so we're commenting it out
#- name: docker-compose up
# ansible.builtin.command: docker compose up -d
# retries: 5
# delay: 5

- name: Git clone repos (retry on failure)
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "/home/vagrant/{{ item.split('/')[-1] }}"
  retries: 3
  delay: 3
  debugger: on_failed
  loop:
    - https://github.com/archcloudlabs/r2elk
  tags:
    - git

- name: Remove cuckcoo yara rules
  ansible.builtin.command: rm ./r2elk/rules/malware/MALW_AZORULT.yar
  tags:
    - git

- name: Install dependencies for r2elk
  ansible.builtin.pip:
    requirements: /home/vagrant/r2elk/requirements.txt
  become: false
  tags:
    - r2elk

- name: Fix permissions
  ansible.builtin.command: chown vagrant:vagrant -R /home/vagrant/
  become: true
